apiVersion: v1
kind: Namespace
metadata:
  name: team-acacia
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-acacia
  namespace: team-acacia
  labels:
    app: team-acacia
spec:
  selector:
    matchLabels:
      app: team-acacia
  replicas: 1
  strategy: 
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25% 
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app:  team-acacia
    spec:
      containers:
      - name: team-acacia
        image: httpd:2.4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
          name: team-acacia
        imagePullPolicy: Always
      restartPolicy: Always

---
apiVersion: v1 
kind: Service 
metadata: 
  name: team-acacia 
  namespace: team-acacia 
spec: 
  selector: 
    app: team-acacia 
  type: LoadBalancer 
  sessionAffinity: None 
  sessionAffinityConfig: 
    clientIP: 
      timeoutSeconds: 10800 
  ports: 
  - name: team-acacia 
    protocol: TCP 
    port: 80
    targetPort: 80 
