apiVersion: v1
kind: Namespace
metadata:
  name: team-acacia
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acacian-hotelapp
  namespace: team-acacia
  labels:
    app: acacian-hotelapp
spec:
  selector:
    matchLabels:
      app: acacian-hotelapp
  replicas: 1
  strategy: 
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25% 
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app:  acacian-hotelapp
    spec:
      containers:
      - name: acacian-hotelapp
        image: k8s.gcr.io/echoserver:1.4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8000
          name: acacian-hotelapp
        imagePullPolicy: Always
      restartPolicy: Always

---
apiVersion: v1 
kind: Service 
metadata: 
  name: acacian-hotelapp 
  namespace: team-acacia 
spec: 
  selector: 
    app: acacian-hotelapp 
  type: LoadBalancer 
  sessionAffinity: None 
  sessionAffinityConfig: 
    clientIP: 
      timeoutSeconds: 10800 
  ports: 
  - name: acacian-hotelapp 
    protocol: TCP 
    port: 80 
    targetPort: 8000 
